name: Franklin Bynum
favicon: null
layout_spectrum: 0.38815694907680154
typography_spectrum: 0.9394575906917453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7351779609452933
  lightness: 0.9951515453867614
  saturation: 0.5389961637556553
  rhythmicContrast: 0.17241918481886387
purpose: []
